# SPDX-License-Identifier: AGPL-3.0-only

name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: "ubuntu-latest"
    steps:

      - uses: "actions/checkout@v2.3.4"

      - uses: "cachix/install-nix-action@v13"

      - uses: "actions/cache@v2"
        with:
          path: "nix-shell.nar"
          key: "${{ runner.os }}-test-nix-shell"

      - name: "Restore Nix shell"
        run: "nix-store --restore nix-shell.nar"

      - name: "Build and test the software"
        run: "nix-shell --argstr profile ci_tests --pure --run 'scripts/ci/tests.bash'"

      - name: "Dump Nix shell"
        run: "nix-store --dump \"$(nix-build --no-out-link shell.nix --argstr profile ci_tests)\" > nix-shell.nar"

  db-setup:
    runs-on: "ubuntu-latest"
    steps:

      - uses: "actions/checkout@v2.3.4"

      - uses: "cachix/install-nix-action@v13"

      - uses: "actions/cache@v2"
        with:
          path: "nix-shell.nar"
          key: "${{ runner.os }}-db-setup-nix-shell"

      - name: "Restore Nix shell"
        run: "nix-store --restore nix-shell.nar"

      - name: "Verify that the database can be set up"
        run: "nix-shell --argstr profile ci_db_setup --pure --run 'scripts/ci/db-setup.bash'"

      - name: "Dump Nix shell"
        run: "nix-store --dump \"$(nix-build --no-out-link shell.nix --argstr profile ci_db_setup)\" > nix-shell.nar"
