name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.3.4"
      - uses: "cachix/install-nix-action@v13"
      - name: "Build and test the software"
        run: "nix-shell --pure --run 'scripts/ci.bash'"
