# SPDX-License-Identifier: AGPL-3.0-only

name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.3.4"
      - uses: "cachix/install-nix-action@v13"
      - name: "Build and test the software"
        run: "nix-shell --argstr profile ci-test --pure --run scripts/ci/test.bash"
  db-setup:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.3.4"
      - uses: "cachix/install-nix-action@v13"
      - name: "Verify that the database can be set up"
        run: "nix-shell --argstr profile ci-db-setup --pure --run scripts/ci/db-setup.bash"
